name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependensies
        run: dotnet restore Onit.sin

      - name: Build project
        run: dotnet build Onit.sin --configuration Release --no-restore

      - name: Run tests
        run: dotnet test Onit.sin --no-build --verbosity normal
